### ISSUE TITLE
Can't generate a song, audio separator fails.

### ISSUE THREAD

**Issue by Werlored** [JackismyShephard/ultimate-rvc#193]
Have tried on windows and linux, and I get the same error, the file is empty when i checked.
I tried to do it manually with audio-separator and it worked.

**Logs:**
2025-04-30 10:19:01 - INFO - httpx - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"
2025-04-30 10:19:02 - INFO - httpx - HTTP Request: GET http://127.0.0.1:7860/gradio_api/startup-events "HTTP/1.1 200 OK"
2025-04-30 10:19:02 - INFO - httpx - HTTP Request: HEAD http://127.0.0.1:7860/ "HTTP/1.1 200 OK"
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Separator version 0.31.1 instantiating with output_dir: C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5, output_format: wav
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Using model directory from model_file_dir parameter: C:\Users\admin\ultimate-rvc\models\audio_separator
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Operating System: Windows 10.0.19045
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - System: Windows Node: DESKTOP- Release: 10 Machine: AMD64 Proc: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Python Version: 3.12.9
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - PyTorch Version: 2.7.0+cu128
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - FFmpeg installed: ffmpeg version 5.0-full_build-www.gyan.dev Copyright (c) 2000-2022 the FFmpeg developers
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - ONNX Runtime GPU package installed with version: 1.20.1
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - CUDA is available in Torch, setting Torch device to CUDA
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - ONNXruntime has CUDAExecutionProvider available, enabling acceleration
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Loading model UVR-MDX-NET-Voc_FT.onnx...
2025-04-30 10:19:22 - INFO - audio_separator.separator.separator - Hash of model file C:\Users\admin\ultimate-rvc\models\audio_separator\UVR-MDX-NET-Voc_FT.onnx is 77d07b2667ddf05b9e3175941b4454a0
2025-04-30 10:19:27 - WARNING - audio_separator.separator.separator - Model converted from onnx to pytorch due to segment size not matching dim_t, processing may be slower.
2025-04-30 10:19:27 - INFO - audio_separator.separator.separator - Load model duration: 00:00:05
2025-04-30 10:19:27 - INFO - audio_separator.separator.separator - Starting separation process for audio_file_path: C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\00_backwards.flac
2025-04-30 10:21:12 - INFO - audio_separator.separator.separator - Saving Instrumental stem to C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Secondary_16f92bdbfd.wav...
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Audio duration is 0.04 hours (138.86 seconds).
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Using pydub for writing.
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Saving Vocals stem to C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Primary_16f92bdbfd.wav...
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Audio duration is 0.04 hours (138.86 seconds).
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Using pydub for writing.
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Clearing input audio file paths, sources and stems...
2025-04-30 10:21:13 - INFO - audio_separator.separator.separator - Separation duration: 00:01:46
2025-04-30 10:21:14 - INFO - audio_separator.separator.separator - Loading model UVR_MDXNET_KARA_2.onnx...
2025-04-30 10:21:14 - INFO - audio_separator.separator.separator - Hash of model file C:\Users\admin\ultimate-rvc\models\audio_separator\UVR_MDXNET_KARA_2.onnx is 1d64a6d2c30f709b8c9b4ce1366d96ee
2025-04-30 10:21:14 - WARNING - audio_separator.separator.separator - Model converted from onnx to pytorch due to segment size not matching dim_t, processing may be slower.
2025-04-30 10:21:14 - INFO - audio_separator.separator.separator - Load model duration: 00:00:00
2025-04-30 10:21:14 - INFO - audio_separator.separator.separator - Starting separation process for audio_file_path: C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Primary_16f92bdbfd.wav
2025-04-30 10:21:14 - ERROR - audio_separator.separator.separator - Audio file C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Primary_16f92bdbfd.wav is empty or not valid

**Error:**
[~] Retrieving song...
[~] Separating vocals from instrumentals...
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [01:40<00:00,  6.27s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 13/13 [00:04<00:00,  3.02it/s]
[~] Separating main vocals from backup vocals...
2025-04-30 09:38:00 - ERROR - audio_separator.separator.separator - Audio file C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Primary_16f92bdbfd.wav is empty or not valid
Traceback (most recent call last):
  File "C:\Users\admin\ultimate-rvc\src\ultimate_rvc\web\common.py", line 70, in _wrapped_fn
    res = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\src\ultimate_rvc\core\generate\song_cover.py", line 1039, in run_pipeline
    backup_vocals_track, main_vocals_track = separate_audio(
                                             ^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\src\ultimate_rvc\core\generate\song_cover.py", line 622, in separate_audio
    audio_separator.separate(
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\audio_separator\separator\separator.py", line 784, in separate
    output_files = self.model_instance.separate(audio_file_path, custom_output_names)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\audio_separator\separator\architectures\mdx_separator.py", line 152, in separate
    mix = self.prepare_mix(self.audio_file_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\audio_separator\separator\common_separator.py", line 220, in prepare_mix
    raise ValueError(error_msg)
ValueError: Audio file C:\Users\admin\ultimate-rvc\audio\intermediate\f428b1fce5\11_Stem_Primary_16f92bdbfd.wav is empty or not valid

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\gradio\queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\gradio\route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\gradio\blocks.py", line 2136, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\gradio\blocks.py", line 1662, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 2470, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 967, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\uv\.venv\Lib\site-packages\gradio\utils.py", line 883, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\ultimate-rvc\src\ultimate_rvc\web\common.py", line 77, in _wrapped_fn
    raise gr.Error(str(e)) from e
gradio.exceptions.Error: 'Audio file C:\\Users\\admin\\ultimate-rvc\\audio\\intermediate\\f428b1fce5\\11_Stem_Primary_16f92bdbfd.wav is empty or not valid'

**Comment by JackismyShephard** [comment]
Hi @Werlored !

Sorry to hear about your issue. Are you sure you are on the latest version of Ultimate RVC? I actually broke the app two days ago but I reverted my changes later. If possible send me a link or upload the song you want to convert and I will try to run it myself to troubleshoot.

**Comment by Werlored** [comment]
It says it up to date, and I have tested multi versions of it 0.5.2, 0.5.5, 0.5.6, 0.5.8, it does not matter which song I take, it does it to all of them tested flac and mp3 and I tested to use a YT link and it didn't work either. AICoverGen and RVC-Project does work but they do not have the features this have.
https://www.youtube.com/watch?v=oh7no6Klxs8

**Comment by JackismyShephard** [comment]
@Werlored Thank you for the link. I will test now.

**Comment by Werlored** [comment]
I use the WebGui locally
My CPU is AMD FX-6350 and GPU GTX1660 6GB VRam, when its separates it uses the CPU, I have better pc 2080s i7-9700k. But can it really be that problem when I tested the other ones or just use the audio-separator manually it works

**Comment by JackismyShephard** [comment]
@Werlored The issue should be fixed now. The error was indeed mine. I recently changed one of this projects dependencies to be a github repository instead of what was formerly a PyPI package. For that to work with pip you would need to install the git-based dependency manually before installing ultimate-rvc. Anyways I switched back. Sorry for the inconvenience 😄

**Comment by JackismyShephard** [comment]
Although the thing about separation using CPU sounds strange. Let me know if things are fixed.

**Comment by Werlored** [comment]
It uses the CPU to separate

![Image](https://github.com/user-attachments/assets/f3bf4319-6031-44d5-a4ce-7149991a5513)

I have tested on both on windows and linux, and still get the same result. I use the PyPI package on linux

is it becouse of this:
WARNING - audio_separator.separator.separator - Model converted from onnx to pytorch due to segment size not matching dim_t, processing may be slower.

**Comment by Werlored** [comment]
This on AMD have not tested the on the intel one at all just the AMD one, Can't test the Intel one until tomorrow

**Comment by JackismyShephard** [comment]
@Werlored Alright, let me know tomorrow if it works on intel. I have a suspicion its might be the framework that Ultimate RVC uses for audio separation that is a bit buggy. AICovenGen does not use that framework.

**Comment by JackismyShephard** [comment]
@Werlored I just reread your first message. Did you mean that you have tried using this https://github.com/nomadkaraoke/python-audio-separator manually? Because if that works its quite strange.

**Comment by Werlored** [comment]
Yeah, in linux I installed your ultimate-rvc PyPI package, and then when the separation failed I just tired it manually in the same .venv

**Comment by JackismyShephard** [comment]
Did you use the same separation model (MDX_NET_VOC_FT)? Also, can you try and set denoise to true and use_autocast to true? Those are the settings Ultimate RVC is using so useful for debugging to know if that fails for you.

**Comment by Werlored** [comment]
It works on the Intel.

AMD:
It seems that use_autocast is the problem because when I set that to false it worked,  in config files of Ultimate RVC

denoise set to true works.



I used this and it works:
audio-separator --use_autocast --mdx_enable_denoise "/home/welo/Skrivbord/lataranvanda/JVNA - Taking It Slow [NCS Release].mp3" --model_file_dir /home/welo/models/audio_separator/ --model_filename UVR-MDX-NET-Voc_FT.onnx

**Comment by JackismyShephard** [comment]
@Werlored that is very good to hear. Auto cast is not that important. I will disable it and publish a new version of ultimate rvc later today.

**Comment by Werlored** [comment]
Thank you for the help. Is it possible to make it a togglable for those with tensor cores cards in the future?

**Comment by JackismyShephard** [comment]
Well I have experimented myself and the gains with autocast are minimal so I think it's fine just to disable for now. There is also a bug in audio separator that makes batch processing not work. Once that works I imagine there will be much greater speed ups (when using GPU)

**Comment by JackismyShephard** [comment]
@Werlored I will close this now
